services:
  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: unless-stopped
    env_file:
    - .env
    networks:
      - backend
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL","mysqladmin ping -h localhost -u root -p$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  wordpress:
    image: wordpress:6.5-php8.2-fpm
    container_name: wordpress_app2
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${MYSQL_DATABASE}
    networks:
      - backend
      - frontend
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy

  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - frontend
    depends_on:
      - wordpress

networks:
  backend:
    internal: true
  frontend:
volumes:
  mysql_data:
  wordpress_data: