name: Wordpress CI-CD pipeline

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: wp_user
          MYSQL_PASSWORD: wp_pw
          MYSQL_DATABASE: my_db
        ports:
          - "3306:3306"
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install mysql-client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Wait for MySql
        run: |
          for i in {1..15}; do
            if mysqladmin ping -h 127.0.0.1 -u root -proot; then
              echo "MySql is up and running.."
              exit 0
            fi
            echo "Waiting for MySql.."
            sleep 3
          done
          echo "MySql connection failed.."
          exit 1
          
      - name: Test DB connection
        run: mysql -h 127.0.0.1 -u root -proot -e "SHOW DATABASES;"
      
  integration-test:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create .env
        run: |
          echo "MYSQL_ROOT_PASSWORD=root">>.env
          echo "MYSQL_USER=wp_user">>.env
          echo "MYSQL_PASSWORD=wp_pw">>.env
          echo "MYSQL_DATABASE=my_db">>.env

      - name: Start services
        run: docker compose up -d

      - name: Wait and check wordpress
        run: |
          for i in {1..20}; do
            if curl -f "http://localhost"; then
              echo "Wordpress is up.."
              exit 0
            fi
            echo "Waiting for wordpress.."
            sleep 3
          done
          echo "Wordpress check failed.."
          exit 1

      - name: Stop services
        if: always()
        run: docker compose down

  build-and-push:
    runs-on: ubuntu-latest
    needs: integration-test

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Tag
        id: vars
        run: echo "TAG=${{ github.sha }}">>$GITHUB_OUTPUT

      - name: Build frontend image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest \
          -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ steps.vars.outputs.TAG }} ./nginx

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Docker push
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ steps.vars.outputs.TAG }} 
